### ISSUE TITLE
bruh did you just invited me for no reason

### ISSUE THREAD

**Issue by SngZongYang** [Alloy177/Alloy#1]

**Comment by Alloy177** [comment]
em i invited you cos i needed your project code etc

**Comment by Alloy177** [comment]
Like can give me your personal account

**Comment by Alloy177** [comment]
Cos like i need to show some coding as some SIL task done

**Comment by SngZongYang** [comment]
I thought you already had them

**Comment by Alloy177** [comment]
I cant find it

**Comment by Alloy177** [comment]
Lmao

**Comment by Alloy177** [comment]
Like code said it is imcomplete :(

**Comment by SngZongYang** [comment]
its there i swear

**Comment by Alloy177** [comment]
just discuss this i school tomorrow. I am dead cos only did 2 sil session 👎

**Comment by SngZongYang** [comment]
just open the src folder

**Comment by Alloy177** [comment]
I cant find stuff lol gotta run either way its Chinese tuition

**Comment by Alloy177** [comment]
like soon so yah bye see ya in shool tomorrow

**Comment by SngZongYang** [comment]
ok

**Comment by Alloy177** [comment]
Alright u onlie?

**Comment by SngZongYang** [comment]
yes

**Comment by Alloy177** [comment]
Give me your code

**Comment by Alloy177** [comment]
:)

**Comment by SngZongYang** [comment]
i deleted it

**Comment by Alloy177** [comment]
You idoit

**Comment by Alloy177** [comment]
Get it back you ******

**Comment by SngZongYang** [comment]
ok

**Comment by Alloy177** [comment]
you a******

**Comment by Alloy177** [comment]
what is forking ah?

**Comment by SngZongYang** [comment]
ok the code is there
